# Generated by Django 5.0.6 on 2024-07-25 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_studentdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdiscount',
            name='channel_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='message_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
