# Generated by Django 5.0.6 on 2024-07-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_studentdiscount_channel_id_studentdiscount_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdiscount',
            name='user',
        ),
    ]
