# Generated by Django 5.0.6 on 2024-07-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_studentdiscount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdiscount',
            name='channel_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='discount_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
